In [ ]:
# Ruchika Bhat  25070123095
# Aim : Data Normalization and Data Type Conversion

In [ ]:
# PART-A
# dataset
import pandas as pd
import numpy as np

data = {
'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
'Price':[55000,20000,30000,2000,8000,45000],
'Units_Sold':[25,60,35,80,50,15],
'Discount':[10,15,12,20,18,8]
}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
# min-max normalization (prize)

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print(df[['Product','Price','Price_MinMax']])

# (units_sold)
df['Units_Sold_MinMax'] = (df['Units_Sold'] - df['Units_Sold'].min()) / (df['Units_Sold'].max() - df['Units_Sold'].min())
print(df[['Product','Units_Sold','Units_Sold_MinMax']])

# (discount)
df['Discount_MinMax'] = (df['Discount'] - df['Discount'].min()) / (df['Discount'].max() - df['Discount'].min())
print(df[['Product','Discount','Discount_MinMax']])

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321
      Product  Units_Sold  Units_Sold_MinMax
0      Laptop          25           0.153846
1      Mobile          60           0.692308
2      Tablet          35           0.307692
3  Headphones          80           1.000000
4  Smartwatch          50           0.538462
5      Camera          15           0.000000
      Product  Discount  Discount_MinMax
0      Laptop        10         0.166667
1      Mobile        15         0.583333
2      Tablet        12         0.333333
3  Headphones        20         1.000000
4  Smartwatch        18         0.833333
5      Camera         8         0.000000

In [ ]:
# normalize multiple columns  (calculating MinMax for all the input data in one go)

cols = ['Price','Units_Sold','Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print(df_norm)

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
# Z-score normalization (units_sold)

df['Units_ZScore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print(df[['Product','Units_Sold','Units_ZScore']])

# (discount)
df['Discount_ZScore'] = (df['Discount'] - df['Discount'].mean()) / df['Discount'].std()
print(df[['Product','Discount','Discount_ZScore']])

# (price)
df['Price_ZScore'] = (df['Price'] - df['Price'].mean()) / df['Price'].std()
print(df[['Product','Price','Price_ZScore']])

      Product  Units_Sold  Units_ZScore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216
      Product  Discount  Discount_ZScore
0      Laptop        10        -0.821638
1      Mobile        15         0.250064
2      Tablet        12        -0.392957
3  Headphones        20         1.321766
4  Smartwatch        18         0.893085
5      Camera         8        -1.250319
      Product  Price  Price_ZScore
0      Laptop  55000      1.365931
1      Mobile  20000     -0.321396
2      Tablet  30000      0.160698
3  Headphones   2000     -1.189164
4  Smartwatch   8000     -0.899908
5      Camera  45000      0.883838

In [ ]:
# decimal scaling (price) (pickup hghest value)

df['Price_Decimal'] = df['Price'] / 100000
print(df[['Product','Price','Price_Decimal']])

# (units_sold)
df['Units_Sold_Decimal'] = df['Units_Sold'] / 100
print(df[['Product','Units_Sold','Units_Sold_Decimal']])

# (discount)
df['Discount_Decimal'] = df['Discount'] / 100
print(df[['Product','Discount','Discount_Decimal']])

      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45
      Product  Units_Sold  Units_Sold_Decimal
0      Laptop          25                0.25
1      Mobile          60                0.60
2      Tablet          35                0.35
3  Headphones          80                0.80
4  Smartwatch          50                0.50
5      Camera          15                0.15
      Product  Discount  Discount_Decimal
0      Laptop        10              0.10
1      Mobile        15              0.15
2      Tablet        12              0.12
3  Headphones        20              0.20
4  Smartwatch        18              0.18
5      Camera         8              0.08

In [ ]:
# PART-B
# dataset
import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df1 = pd.DataFrame(data)
print(df1)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [ ]:
# method 1: Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['Gender_Label'] = le.fit_transform(df1['Customer_Gender'])
display(df1)
df1['City_Label'] = le.fit_transform(df1['City'])
display(df1)
df1['Product_Category_Label'] = le.fit_transform(df1['Product_Category'])
display(df1)
df1['Payment_Method_Label'] = le.fit_transform(df1['Payment_Method'])
display(df1)

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label,Product_Category_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4,2
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3,1
2,103,Female,Debit Card,Home,Delhi,3200,0,1,3
3,104,Male,COD,Electronics,Bangalore,5200,1,0,2
4,105,Female,UPI,Beauty,Pune,1800,0,4,0
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2,2

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label,Product_Category_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4,2
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3,1
2,103,Female,Debit Card,Home,Delhi,3200,0,1,3
3,104,Male,COD,Electronics,Bangalore,5200,1,0,2
4,105,Female,UPI,Beauty,Pune,1800,0,4,0
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2,2

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label,Product_Category_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4,2
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3,1
2,103,Female,Debit Card,Home,Delhi,3200,0,1,3
3,104,Male,COD,Electronics,Bangalore,5200,1,0,2
4,105,Female,UPI,Beauty,Pune,1800,0,4,0
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2,2

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label,Product_Category_Label,Payment_Method_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4,2,3
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3,1,1
2,103,Female,Debit Card,Home,Delhi,3200,0,1,3,2
3,104,Male,COD,Electronics,Bangalore,5200,1,0,2,0
4,105,Female,UPI,Beauty,Pune,1800,0,4,0,3
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2,2,2

In [ ]:
# method 2: One-Hot Encoding (can apply in multiple columns)

df_encoded = pd.get_dummies(df1, columns=['Customer_Gender','City','Product_Category','Payment_Method'])
display(df_encoded)

,Order_ID,Order_Value,Gender_Label,City_Label,Product_Category_Label,Payment_Method_Label,Customer_Gender_Female,Customer_Gender_Male,City_Bangalore,City_Delhi,...,City_Mumbai,City_Pune,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,4500,1,4,2,3,False,True,False,False,...,False,True,False,False,True,False,False,False,False,True
1,102,2300,0,3,1,1,True,False,False,False,...,True,False,False,True,False,False,False,True,False,False
2,103,3200,0,1,3,2,True,False,False,True,...,False,False,False,False,False,True,False,False,True,False
3,104,5200,1,0,2,0,False,True,True,False,...,False,False,False,False,True,False,True,False,False,False
4,105,1800,0,4,0,3,True,False,False,False,...,False,True,True,False,False,False,False,False,False,True
5,106,4100,1,2,2,2,False,True,False,False,...,False,False,False,False,True,False,False,False,True,False

In [ ]:
# method 3: Dummy Encoding (drops first column)

df_dummy = pd.get_dummies(df1, columns=['Customer_Gender','City','Product_Category','Payment_Method'], drop_first=True)
display(df_dummy)

,Order_ID,Order_Value,Gender_Label,City_Label,Product_Category_Label,Payment_Method_Label,Customer_Gender_Male,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,4500,1,4,2,3,True,False,False,False,True,False,True,False,False,False,True
1,102,2300,0,3,1,1,False,False,False,True,False,True,False,False,True,False,False
2,103,3200,0,1,3,2,False,True,False,False,False,False,False,True,False,True,False
3,104,5200,1,0,2,0,True,False,False,False,False,False,True,False,False,False,False
4,105,1800,0,4,0,3,False,False,False,False,True,False,False,False,False,False,True
5,106,4100,1,2,2,2,True,False,True,False,False,False,True,False,False,True,False

In [ ]:
# PART-C
# data normalization
import pandas as pd
df2 = pd.read_csv('/Student-Dataset.csv')
display(df2)

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
# method 1: Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2['Gender_Label'] = le.fit_transform(df2['Gender'])
display(df2)

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,0
1,102,Male,IT,7.5,1,85,Not Placed,0,1
2,103,Female,ENTC,9.1,0,96,Placed,550000,0
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,1
4,105,Female,Computer,8.7,0,88,Placed,480000,0
5,106,Male,Civil,7.2,3,72,Not Placed,0,1
6,107,Female,IT,8.9,0,91,Placed,500000,0
7,108,Male,Computer,6.5,1,80,Not Placed,0,1
8,109,Female,ENTC,7.8,0,84,Placed,420000,0
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,1

In [ ]:
# method 2: One-Hot Encoding (can apply in multiple columns)

df_encoding = pd.get_dummies(df2, columns=['Gender','Department','Placement_Status'])
display(df_encoding)

,Roll_No,CGPA,Number_of_Backlogs,Attendance_Percentage,Salary,Gender_Label,Gender_Female,Gender_Male,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical,Placement_Status_Not Placed,Placement_Status_Placed
0,101,8.2,0,92,450000,0,True,False,False,True,False,False,False,False,True
1,102,7.5,1,85,0,1,False,True,False,False,False,True,False,True,False
2,103,9.1,0,96,550000,0,True,False,False,False,True,False,False,False,True
3,104,6.8,2,78,0,1,False,True,False,False,False,False,True,True,False
4,105,8.7,0,88,480000,0,True,False,False,True,False,False,False,False,True
5,106,7.2,3,72,0,1,False,True,True,False,False,False,False,True,False
6,107,8.9,0,91,500000,0,True,False,False,False,False,True,False,False,True
7,108,6.5,1,80,0,1,False,True,False,True,False,False,False,True,False
8,109,7.8,0,84,420000,0,True,False,False,False,True,False,False,False,True
9,110,7.0,2,76,0,1,False,True,False,False,False,False,True,True,False

In [ ]:
# method 3: Dummy Encoding (drops first column)

df_dum = pd.get_dummies(df2, columns=['Gender','Department','Placement_Status'], drop_first=True)
display(df_dum)

,Roll_No,CGPA,Number_of_Backlogs,Attendance_Percentage,Salary,Gender_Label,Gender_Male,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical,Placement_Status_Placed
0,101,8.2,0,92,450000,0,False,True,False,False,False,True
1,102,7.5,1,85,0,1,True,False,False,True,False,False
2,103,9.1,0,96,550000,0,False,False,True,False,False,True
3,104,6.8,2,78,0,1,True,False,False,False,True,False
4,105,8.7,0,88,480000,0,False,True,False,False,False,True
5,106,7.2,3,72,0,1,True,False,False,False,False,False
6,107,8.9,0,91,500000,0,False,False,False,True,False,True
7,108,6.5,1,80,0,1,True,True,False,False,False,False
8,109,7.8,0,84,420000,0,False,False,True,False,False,True
9,110,7.0,2,76,0,1,True,False,False,False,True,False

In [ ]:
# PART-D
# data type conversion

import pandas as pd
import numpy as np
df3 = pd.read_csv('/amazon_products_dataset_Expt-14.csv')
display(df3)

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
# min-max normalization (reviews)

df3['Reviews_MinMax'] = (df3['Reviews'] - df3['Reviews'].min()) / (df3['Reviews'].max() - df3['Reviews'].min())
print(df3[['Product_ID','Reviews','Reviews_MinMax']])

   Product_ID  Reviews  Reviews_MinMax
0        P101     1520        0.291005
1        P102      980        0.148148
2        P103      870        0.119048
3        P104     2100        0.444444
4        P105     3050        0.695767
5        P106     1750        0.351852
6        P107      620        0.052910
7        P108     1120        0.185185
8        P109     1850        0.378307
9        P110      760        0.089947
10       P111     4200        1.000000
11       P112     2100        0.444444
12       P113     1300        0.232804
13       P114      540        0.031746
14       P115      870        0.119048
15       P116     2300        0.497354
16       P117      760        0.089947
17       P118     1600        0.312169
18       P119     3500        0.814815
19       P120      980        0.148148
20       P121      420        0.000000
21       P122     1450        0.272487
22       P123     1250        0.219577
23       P124      720        0.079365
24       P125     2100        0.444444
25       P126      980        0.148148
26       P127     3100        0.708995
27       P128     1300        0.232804
28       P129      880        0.121693
29       P130      990        0.150794
30       P131     2100        0.444444
31       P132     1750        0.351852
32       P133     2500        0.550265
33       P134     1450        0.272487
34       P135     2100        0.444444
35       P136      450        0.007937
36       P137      900        0.126984
37       P138      600        0.047619
38       P139      720        0.079365
39       P140      520        0.026455
40       P141      850        0.113757
41       P142     1200        0.206349
42       P143     2100        0.444444
43       P144     1800        0.365079
44       P145     1400        0.259259
45       P146     2200        0.470899
46       P147     1650        0.325397
47       P148      980        0.148148
48       P149      870        0.119048
49       P150      760        0.089947

In [ ]:
# normalize multiple columns  (calculating MinMax for all the input data in one go)

columns = ['Price','Units_Sold']
df3_normal = (df3[columns] - df3[columns].min()) / (df3[columns].max() - df3[columns].min())
print(df3_normal)

       Price  Units_Sold
0   0.020243    0.518519
1   0.048583    0.277778
2   0.016194    0.203704
3   0.089069    0.629630
4   0.149798    0.833333
5   0.036437    0.592593
6   0.024291    0.129630
7   0.064777    0.351852
8   0.210526    0.481481
9   0.028340    0.222222
10  0.311741    1.000000
11  0.174089    0.407407
12  0.052632    0.500000
13  0.016194    0.092593
14  0.024291    0.240741
15  0.251012    0.444444
16  0.036437    0.259259
17  0.068826    0.648148
18  0.109312    0.851852
19  0.040486    0.351852
20  0.008097    0.148148
21  0.089069    0.444444
22  0.352227    0.185185
23  0.020243    0.259259
24  0.129555    0.592593
25  0.174089    0.166667
26  0.514170    0.129630
27  0.076923    0.370370
28  0.016194    0.314815
29  0.048583    0.351852
30  0.392713    0.240741
31  0.230769    0.203704
32  0.129555    0.666667
33  0.473684    0.092593
34  0.635628    0.037037
35  0.012146    0.166667
36  0.020243    0.462963
37  0.000000    0.574074
38  0.028340    0.259259
39  0.048583    0.111111
40  0.109312    0.148148
41  0.433198    0.074074
42  0.190283    0.351852
43  1.000000    0.000000
44  0.068826    0.444444
45  0.311741    0.240741
46  0.757085    0.092593
47  0.089069    0.185185
48  0.129555    0.148148
49  0.028340    0.314815

In [ ]:
# Z-score normalization (units_sold)

df3['Units_ZScore.norm'] = (df3['Units_Sold'] - df3['Units_Sold'].mean()) / df3['Units_Sold'].std()
print(df3[['Product_ID','Units_Sold','Units_ZScore.norm']])

   Product_ID  Units_Sold  Units_ZScore.norm
0        P101         350           0.812282
1        P102         220          -0.260855
2        P103         180          -0.591051
3        P104         410           1.307576
4        P105         520           2.215615
5        P106         390           1.142478
6        P107         140          -0.921247
7        P108         260           0.069341
8        P109         330           0.647184
9        P110         190          -0.508502
10       P111         610           2.958556
11       P112         290           0.316988
12       P113         340           0.729733
13       P114         120          -1.086345
14       P115         200          -0.425953
15       P116         310           0.482086
16       P117         210          -0.343404
17       P118         420           1.390125
18       P119         530           2.298164
19       P120         260           0.069341
20       P121         150          -0.838698
21       P122         310           0.482086
22       P123         170          -0.673600
23       P124         210          -0.343404
24       P125         390           1.142478
25       P126         160          -0.756149
26       P127         140          -0.921247
27       P128         270           0.151890
28       P129         240          -0.095757
29       P130         260           0.069341
30       P131         200          -0.425953
31       P132         180          -0.591051
32       P133         430           1.472674
33       P134         120          -1.086345
34       P135          90          -1.333992
35       P136         160          -0.756149
36       P137         320           0.564635
37       P138         380           1.059929
38       P139         210          -0.343404
39       P140         130          -1.003796
40       P141         150          -0.838698
41       P142         110          -1.168894
42       P143         260           0.069341
43       P144          70          -1.499090
44       P145         310           0.482086
45       P146         200          -0.425953
46       P147         120          -1.086345
47       P148         170          -0.673600
48       P149         150          -0.838698
49       P150         240          -0.095757

In [ ]:
# decimal scaling (price) (pickup hghest value)

df3['Price_Deci'] = df3['Price'] / 100000
print(df3[['Product_ID','Price','Price_Deci']])

   Product_ID  Price  Price_Deci
0        P101    799     0.00799
1        P102   1499     0.01499
2        P103    699     0.00699
3        P104   2499     0.02499
4        P105   3999     0.03999
5        P106   1199     0.01199
6        P107    899     0.00899
7        P108   1899     0.01899
8        P109   5499     0.05499
9        P110    999     0.00999
10       P111   7999     0.07999
11       P112   4599     0.04599
12       P113   1599     0.01599
13       P114    699     0.00699
14       P115    899     0.00899
15       P116   6499     0.06499
16       P117   1199     0.01199
17       P118   1999     0.01999
18       P119   2999     0.02999
19       P120   1299     0.01299
20       P121    499     0.00499
21       P122   2499     0.02499
22       P123   8999     0.08999
23       P124    799     0.00799
24       P125   3499     0.03499
25       P126   4599     0.04599
26       P127  12999     0.12999
27       P128   2199     0.02199
28       P129    699     0.00699
29       P130   1499     0.01499
30       P131   9999     0.09999
31       P132   5999     0.05999
32       P133   3499     0.03499
33       P134  11999     0.11999
34       P135  15999     0.15999
35       P136    599     0.00599
36       P137    799     0.00799
37       P138    299     0.00299
38       P139    999     0.00999
39       P140   1499     0.01499
40       P141   2999     0.02999
41       P142  10999     0.10999
42       P143   4999     0.04999
43       P144  24999     0.24999
44       P145   1999     0.01999
45       P146   7999     0.07999
46       P147  18999     0.18999
47       P148   2499     0.02499
48       P149   3499     0.03499
49       P150    999     0.00999